// src/components/aboutMe/index.tsx
'use client';

import { motion, useInView } from 'framer-motion';
import { useRef } from 'react';
import { H2 } from '../ui/h2';
import './aboutMe.css';
import FundoColorido from '../fundoColorido';

const AboutMe = () => {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true });

  return (
    <FundoColorido id='containeAbout' className='grid place-items-center'>
      <div className='mx-auto max-w-7xl px-6 md:px-12 pt-12 pb-6 md:pb-12 flex flex-col items-center justify-center gap-10'>
        <H2 className='text-white drop-shadow-sm drop-shadow-black/25 tracking-wider text-center'>
          About me
        </H2>
        <motion.div
          ref={ref}
          initial={{ opacity: 0, y: 150 }}
          animate={isInView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 1, ease: [0.22, 1, 0.36, 1] }}
          className='shadow-xl rounded-xl font-mono'
        >
          <div className='h-14 bg-white gap-4 px-5 rounded-t-xl flex justify-start items-center'>
            <span className='bg-red-500 w-4 aspect-square rounded-full block'></span>
            <span className='bg-yellow-400 w-4 aspect-square rounded-full block'></span>
            <span className='bg-green-400 w-4 aspect-square rounded-full block'></span>
          </div>
          <div className='containerCodigo font-semibold h-full text-white p-7 bg-gray-900 rounded-b-xl'>
            <span className='ponto'>{'{'}</span>
            <div>
              <p>
                &quot;full-name&quot;<span className='ponto'>: </span>
                <span> &quot;João Vitor Carmassi&quot;</span>
                <span className='virgula'>,</span>
              </p>
              <p>
                &quot;birthdate&quot;<span className='ponto'>: </span>
                <span>&quot;December 8, 2004&quot;</span>
                <span className='virgula'>,</span>
              </p>
              <p>
                &quot;place-of-birth&quot;<span className='ponto'>: </span>
                <span>&quot;São Paulo, SP&quot;</span>
                <span className='virgula'>,</span>
              </p>
              <p>
                &quot;where-I-live&quot;<span className='ponto'>: </span>
                <span>&quot;São Bento do Sapucai, SP&quot;</span>
                <span className='virgula'>,</span>
              </p>
              <p>
                &quot;languages&quot;<span className='ponto'>: </span>
                <span className='lista'>{'{'}</span>
              </p>
              <div>
                <p>
                  &quot;english&quot;<span className='ponto'>: </span>
                  <span>&quot;C1&quot;</span>
                  <span className='virgula'>,</span>
                </p>
                <p>
                  &quot;spanish&quot;<span className='ponto'>: </span>
                  <span>&quot;B2&quot;</span>
                  <span className='virgula'>,</span>
                </p>
              </div>
              <span className='lista'>{'}'}</span>
              <span className='virgula'>,</span>
              <p>
                &quot;technologies&quot;<span className='ponto'>: </span>
                <span className='lista'>[</span>
                <span>
                  &quot;HTML&quot;
                  <span className='virgula'>,</span>
                  &quot;CSS&quot;
                  <span className='virgula'>,</span>
                  &quot;Tailwind&quot;
                  <span className='virgula'>,</span>
                  &quot;Sass&quot;
                  <span className='virgula'>,</span>
                  &quot;React&quot;
                  <span className='virgula'>,</span>
                  &quot;Next.Js&quot;
                  <span className='virgula'>,</span>
                  &quot;Git&quot;
                  <span className='virgula'>,</span>
                  &quot;Github&quot;
                  <span className='virgula'>,</span>
                  &quot;Eslint&quot;
                </span>
                <span className='lista'>]</span>
                <span className='virgula'>,</span>
              </p>
              <p>
                &quot;interests&quot;<span className='ponto'>: </span>
                <span className='lista'>[</span>
              </p>
              <div>
                <p>
                  <span>&quot;Programming&quot;</span>
                  <span className='virgula'>,</span>
                </p>
                <p>
                  <span>&quot;Games&quot;</span>
                  <span className='virgula'>,</span>
                </p>
                <p>
                  <span>&quot;Anime&quot;</span>
                  <span className='virgula'>,</span>
                </p>
                <p>
                  <span>&quot;Music&quot;</span>
                  <span className='virgula'>,</span>
                </p>
                <p>
                  <span>&quot;Movies&quot;</span>
                  <span className='virgula'>,</span>
                </p>
                <p>
                  <span>&quot;Hiking&quot;</span>
                  <span className='virgula'>,</span>
                </p>
                <p>
                  <span>&quot;Technology&quot;</span>
                  <span className='virgula'>,</span>
                </p>
                <p>
                  <span>&quot;Meeting new people and places&quot;</span>
                  <span className='virgula'>,</span>
                </p>
              </div>
              <span className='lista'>]</span>
              <span className='virgula'>,</span>
            </div>
            <span className='ponto'>{'}'}</span>
            <span className='virgula'>,</span>
          </div>
        </motion.div>
      </div>
    </FundoColorido>
  );
};

export default AboutMe;

// src/components/AboutMe.vue
<template>
  <div class="w-full flex justify-center items-center flex-col">
    <div>
      <h2 class="text-white font-semibold drop-shadow-md my-10 text-4xl">
        About Me:
      </h2>
    </div>
    <div class="mx-4 shadow-xl mb-20 md:w-1/2 h-fit bg-base-100 rounded-xl">
      <div
        class="h-14 bg-white gap-4 px-5 rounded-t-xl flex justify-start items-center"
      >
        <span class="bg-red-500 w-4 aspect-square rounded-full block"></span>
        <span class="bg-yellow-400 w-4 aspect-square rounded-full block"></span>
        <span class="bg-green-400 w-4 aspect-square rounded-full block"></span>
      </div>
      <div
        class="containerCodigo font-semibold w-full h-full text-white p-7 bg-gray-900 rounded-b-xl"
      >
        <span class="ponto">{</span>
        <div>
          <p>
            "full-name"<span class="ponto">: </span>
            <span> "João Vitor Carmassi"</span><span class="virgula">,</span>
          </p>
          <p>
            "birthdate"<span class="ponto">: </span>
            <span>"December 8, 2004"</span><span class="virgula">,</span>
          </p>
          <p>
            "place-of-birth"<span class="ponto">: </span>
            <span>"São Paulo, SP"</span><span class="virgula">,</span>
          </p>
          <p>
            "where-I-live"<span class="ponto">: </span>
            <span>"São Bento do Sapucai, SP"</span
            ><span class="virgula">,</span>
          </p>
          <p>
            "languages"<span class="ponto">: </span>
            <span class="lista">{</span>
          </p>
          <div>
            <p>
              "english"<span class="ponto">: </span><span>"B2"</span
              ><span class="virgula">,</span>
            </p>
            <p>
              "spanish"<span class="ponto">: </span><span>"B2"</span
              ><span class="virgula">,</span>
            </p>
          </div>
          <span class="lista">}</span><span class="virgula">,</span>
          <p>
            "technologies"<span class="ponto">: </span>
            <span class="lista">[</span>
            <span>
              "Tailwind"
              <span class="virgula">,</span>
              "Boostrap"
              <span class="virgula">,</span>
              "Sass"
              <span class="virgula">,</span>
              "Vue"
              <span class="virgula">,</span>
              "Git" </span
            ><span class="lista">]</span><span class="virgula">,</span>
          </p>
          <p>
            "interests"<span class="ponto">: </span>
            <span class="lista">[</span>
          </p>
          <div>
            <p><span>"Programming"</span><span class="virgula">,</span></p>
            <p><span>"Games"</span><span class="virgula">,</span></p>
            <p><span>"Anime"</span><span class="virgula">,</span></p>
            <p><span>"Music"</span><span class="virgula">,</span></p>
            <p><span>"Movies"</span><span class="virgula">,</span></p>
            <p><span>"Hiking"</span><span class="virgula">,</span></p>
            <p><span>"Technology"</span><span class="virgula">,</span></p>
            <p>
              <span>"Meeting new people and places"</span
              ><span class="virgula">,</span>
            </p>
          </div>
          <span class="lista">]</span><span class="virgula">,</span>
        </div>
        <span class="ponto">}</span><span class="virgula">,</span>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
export default {};
</script>

<style scoped>
.containerCodigo {
  & div {
    margin-left: 2rem;
  }

  & .ponto {
    color: #d272c6;
  }

  & .lista {
    color: #179fe1;
  }

  & .virgula {
    color: white;
  }

  & p {
    color: #988bc7;
  }

  & span {
    color: #e7de79;
  }
}
</style>
