// src/components/fundoColorido.tsx
'use client';

import adicionaFundoColorido from '@/utils/fundoColorido';
import { ReactNode, HTMLAttributes, useEffect } from 'react';

interface FundoColoridoProps extends HTMLAttributes<HTMLElement> {
  children?: ReactNode;
  className?: string;
}

const FundoColorido: React.FC<FundoColoridoProps> = ({
  children,
  className,
  ...props
}) => {
  useEffect(() => {
    adicionaFundoColorido();
  }, []);

  return (
    <section
      {...props}
      className={`header finisher-header relative ${className}`}
    >
      {children}
    </section>
  );
};

export default FundoColorido;

// src/components/FundoColorido.vue
<template>
  <section class="relative">
    <ShapeDivider />
    <div class="header finisher-header w-full h-full">
      <slot></slot>
    </div>
  </section>
</template>
<script lang="ts">
import adicionaFundoColorido from "@/util/fundoColorido";
import ShapeDivider from "./ShapeDivider.vue";

export default {
  components: {
    ShapeDivider,
  },
  mounted() {
    adicionaFundoColorido();
  },
};
</script>
