// src/components/repsGraph/index.tsx
'use client';

import IUserGithub from '@/types/IUser';
import axios from 'axios';
import { useEffect, useState, useRef } from 'react';
import { H2 } from '../ui/h2';
import { Avatar, AvatarFallback, AvatarImage } from '../ui/avatar';
import { ChartLanguages } from './graph';
import { motion, useInView, Variants } from 'framer-motion';

const API_KEY = 'https://api.github.com/users/joao-carmassi';

const baixaUserGithub = () => {
  return axios.get(API_KEY).then((res) => res.data);
};

const RepsGraph = () => {
  const [user, setUser] = useState<undefined | IUserGithub>(undefined);
  const containerRef = useRef(null);
  const isInView = useInView(containerRef, {
    once: true,
    margin: '-250px 0px',
  });

  const itemVariants: Variants = {
    hidden: { opacity: 0, y: 20 },
    visible: (i = 0) => ({
      opacity: 1,
      y: 0,
      transition: { delay: i * 0.15, duration: 0.7, ease: 'easeOut' },
    }),
  };

  useEffect(() => {
    baixaUserGithub().then((res) => {
      setUser(res);
    });
  }, []);

  return (
    <section id='containerGithub' className='bg-background relative'>
      <div className='absolute inset-0 z-0 h-full w-full bg-white bg-[linear-gradient(to_right,#f0f0f0_1px,transparent_1px),linear-gradient(to_bottom,#f0f0f0_1px,transparent_1px)] bg-[size:6rem_4rem]'></div>
      <div className='flex relative z-10 flex-col gap-6 md:gap-12 mx-auto p-6 md:p-12 max-w-7xl'>
        <H2 className='text-center'>Github</H2>
        <div className='shadow-2xl max-w-4xl mx-auto'>
          <header className='bg-primary text-primary-foreground p-5'>
            <div>
              <a
                target='_blank'
                href={user?.html_url}
                className='flex items-center gap-3 group w-fit'
                rel='noreferrer'
              >
                <Avatar className='h-16 w-16 group-hover:ring-2 ring-primary-foreground duration-200'>
                  <AvatarImage src={user?.avatar_url} />
                  <AvatarFallback>{user?.name}</AvatarFallback>
                </Avatar>
                <H2 className='text-primary-foreground group-hover:underline text-lg md:text-xl'>
                  {user?.login}
                </H2>
              </a>
            </div>
          </header>
          <main className='bg-card'>
            <div
              ref={containerRef}
              className='grid grid-cols-1 md:grid-cols-2 gap-4 p-4'
            >
              {[
                { label: 'Reps:', value: user?.public_repos },
                { label: 'Followers:', value: user?.followers },
                { label: 'Following:', value: user?.following },
                { label: 'Location:', value: user?.location },
              ].map((item, i) => (
                <motion.div
                  key={item.label}
                  className='p-4 rounded-lg border border-accent shadow-sm bg-background'
                  initial='hidden'
                  animate={isInView ? 'visible' : 'hidden'}
                  custom={i}
                  variants={itemVariants}
                >
                  <h2 className='text-md font-semibold text-foreground/75'>
                    {item.label}
                  </h2>
                  <p className='text-lg md:text-xl text-primary break-all break-words'>
                    {item.value}
                  </p>
                </motion.div>
              ))}
              <motion.div
                className='col-span-full border border-accent p-4 rounded-lg shadow-sm bg-background'
                initial='hidden'
                animate={isInView ? 'visible' : 'hidden'}
                custom={4}
                variants={itemVariants}
              >
                <h2 className='text-md font-semibold text-foreground/75'>
                  Bio:
                </h2>
                <p className='text-lg md:text-xl text-primary break-all break-words'>
                  {user?.bio}
                </p>
              </motion.div>
            </div>
            <div className='mx-auto max-w-3xl pb-4 pr-14'>
              <ChartLanguages />
            </div>
          </main>
        </div>
      </div>
    </section>
  );
};

export default RepsGraph;

// src/components/RepsGraph.vue
<template>
  <section class="bg-base-100 linhasContainer px-5">
    <div class="py-8 md:py-12 grid place-items-center">
      <h2 class="text-3xl md:text-4xl text-primary font-semibold">Github</h2>
    </div>
    <div class="pb-14 max-w-full md:pb-20 grid place-items-center">
      <div
        id="infoGithub"
        class="shadow-xl md:w-4/5 lg:w-1/2 grid place-items-center"
      >
        <header class="bg-primary w-full flex items-center h-fit p-4 gap-4">
          <a
            :href="user.html_url"
            target="_blank"
            class="hover:ring ring-white duration-300 rounded-full avatar online"
          >
            <div class="w-16 rounded-full">
              <img :src="user.avatar_url" />
            </div>
          </a>
          <h2 class="text-lg text-white font-semibold">{{ user.login }}</h2>
        </header>
        <main class="bg-base-100">
          <div class="grid grid-cols-1 md:grid-cols-2 gap-4 p-4">
            <div class="bg-base-200 p-4 rounded-lg">
              <h3 class="text-md font-semibold text-gray-600">Reps:</h3>
              <p class="text-lg md:text-xl text-primary">
                {{ user.public_repos }}
              </p>
            </div>
            <div class="bg-base-200 p-4 rounded-lg">
              <h3 class="text-md font-semibold text-gray-600">Followers:</h3>
              <p class="text-lg md:text-xl text-primary">
                {{ user.followers }}
              </p>
            </div>
            <div class="bg-base-200 p-4 rounded-lg">
              <h3 class="text-md font-semibold text-gray-600">Following:</h3>
              <p class="text-lg md:text-xl text-primary">
                {{ user.following }}
              </p>
            </div>
            <div class="bg-base-200 p-4 rounded-lg">
              <h3 class="text-md font-semibold text-gray-600">Location:</h3>
              <p class="text-lg md:text-xl text-primary break-all break-words">
                {{ user.location }}
              </p>
            </div>
            <div class="bg-base-200 col-span-full p-4 rounded-lg">
              <h3 class="text-md font-semibold text-gray-600">Bio:</h3>
              <p class="text-lg md:text-xl text-primary break-all break-words">
                {{ user.bio }}
              </p>
            </div>
          </div>
          <div class="px-4 md:w-10/12 mx-auto pb-8 grid place-items-center">
            <canvas id="myChart"></canvas>
          </div>
        </main>
      </div>
    </div>
  </section>
</template>

<script lang="ts">
import type IUserGithub from "@/interface/IUserGithub";
import baixaUserGithub from "@/service/SBaixaUserGithub";
import criaGrafico from "@/util/criaGrafico";

export default {
  data() {
    return {
      user: {} as IUserGithub,
    };
  },
  async mounted() {
    this.user = await baixaUserGithub();
    criaGrafico();
  },
};
</script>

<style scoped>
.linhasContainer {
  width: 100%;
  height: 100%;
  background-image: radial-gradient(rgba(0, 0, 0, 0.171) 2px, transparent 0);
  background-size: 30px 30px;
  background-position: -5px -5px;
}
</style>
